service: budgetwise-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  # The serverless-dotenv-plugin will handle environment variables now
  # So we can remove the explicit environment block from here.

functions:
  app:
    handler: handler.app
    events:
      - http:
          path: /
          method: get
          cors: &corsConfig
            origin: 'https://budgetwise-yash.netlify.app,http://localhost:3000'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
      - http:
          path: /{proxy+}
          method: any
          cors: *corsConfig

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

# Add this custom section at the end of the file
custom:
  dotenv:
    path: ./.env # This tells the plugin where to look for variables

