service: budgetwise-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2


functions:
  app:
    handler: handler.app
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin 

custom:
  dotenv:
    path: ./.env # This tells the plugin where to look for variables