service: budgetwise-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  # The serverless-dotenv-plugin will handle environment variables now
  # So we can remove the explicit environment block from here.
functions:
  app:
    handler: handler.app
    events:
      - http:
          path: /
          method: any # Use 'any' for the root to catch all methods
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true # This is the simplified configuration
# functions:
#   app:
#     handler: handler.app
#     events:
#       - http:
#           path: /
#           method: geta
#           cors:
#             origins:
#               - https://budgetwise-mu.vercel.app
#               - http://localhost:3000
#             headers:
#               - Content-Type
#               - Authorization
#             allowCredentials: true
#       - http:
#           path: /{proxy+}
#           method: any
#           cors:
#             origins:
#               - https://budgetwise-mu.vercel.app
#               - http://localhost:3000
#             headers:
#               - Content-Type
#               - Authorization
#             allowCredentials: true
#       - http:
#           path: /{proxy+}
#           method: options
#           cors: true

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseType: DEFAULT_4XX
        RestApiId: { Ref: ApiGatewayRestApi }
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'https://budgetwise-mu.vercel.app'"
          gatewayresponse.header.Access-Control-Allow-Credentials: "'true'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
    GatewayResponseDefault5XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseType: DEFAULT_5XX
        RestApiId: { Ref: ApiGatewayRestApi }
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'https://budgetwise-mu.vercel.app'"
          gatewayresponse.header.Access-Control-Allow-Credentials: "'true'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"


plugins:
  - serverless-offline
  - serverless-dotenv-plugin

# Add this custom section at the end of the file
custom:
  dotenv:
    path: ./.env # This tells the plugin where to look for variables
  serverless-offline:
    noPrependStageInUrl: true  #This line removes the /dev prefix locally
    httpPort: 5000
